sudo: required

services:
  - docker
env:
  global:
    - IMG=yhnw/openwrt-sdk

before_install:
  - docker version
  - docker pull $IMG
  - docker run --rm -u openwrt -v $PWD:/work $IMG /bin/sh /work/build.sh

script:
  - ls -la
